name: 1.0$(rev:.r) # build numbering format

resources:
  repositories:
  - repository: ALMStuff
    type: github
    name: DrMueller/ALMStuff
    ref: refs/heads/master
    endpoint: GitHub-DrMueller

jobs:
- job: 'BuildAndPublishAzureDevOpsExtension'
  displayName: 'Build and publish Azure DevOps Extension'
  pool:
    name: 'Hosted VS2017'
  steps:
  - template: AzureDevOps/BuildTemplates/Angular/Steps/Git_Config.yaml@ALMStuff
  - template: AzureDevOps/BuildTemplates/Angular/Steps/Initialize.yaml@ALMStuff
  - template: AzureDevOps/BuildTemplates/Angular/Steps/Run_Tests.yaml@ALMStuff
    parameters:
      ExecuteIntegrationTests: true
  - template: AzureDevOps/BuildTemplates/Angular/Steps/Build_Production.yaml@ALMStuff
  - template: AzureDevOps/BuildTemplates/Angular/Steps/Update_NPM_Package_Version.yaml@ALMStuff
    parameters:
      WorkingDir: dist
  - template: AzureDevOps/BuildTemplates/Angular/Steps/Update_Tfx_Version.yaml@ALMStuff
  - template: AzureDevOps/BuildTemplates/Angular/Steps/Publish_Tfx_Package.yaml@ALMStuff